name: Testing
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Testing TS action
        uses: drakonhg/typescript-telegram@v0.1
        with:
          name: "Maria and Buba with Baton"
